name: Deploy on AlmaLinux
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Ant Media Server
      shell: bash
      run: |
        echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        yum -y install wget which
        wget -O ant-media-server-community.zip "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=io.antmedia&a=ant-media-server&v=LATEST&c=community&e=zip";
        bash ./install_ant-media-server.sh -i ant-media-server-community.zip -s false
        /usr/local/antmedia/antmedia start
        sleep 30
        if [ $(cat /usr/local/antmedia/log/ant-media-server.log | grep "LiveApp started" | wc -l | xargs) -eq 0 ]; then 
          echo "LiveApp started log does not exist. Check the logs above"
          exit 1;
        fi;
