name: AlmaLinux
on: [push]
jobs:
  Almalinux8:
    runs-on: ubuntu-20.04
    container: almalinux:8
    steps:
      - uses: ant-media/Scripts/.github/actions/deploy-almalinux@main
#  Almalinux9:
#    runs-on: ubuntu-20.04
#    container: almalinux:9
#    steps:
#      - uses: ant-media/Scripts/.github/actions/deploy-almalinux@main
