name: RockyLinux
on: [push]
#on:
#  push:
#    paths:
#      - 'install_ant-media-server.sh'
jobs:
  RockyLinux8:
    runs-on: ubuntu-20.04
    container: rockylinux:8
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-rockylinux
  RockyLinux9:
    runs-on: ubuntu-20.04
    container: rockylinux:9
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-rockylinux
